# PATH: docker-compose.prod.yml

services:
  frontend:
    build:
      target: prod
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ip-frontend.rule=PathPrefix(`/ip`)"
      - "traefik.http.routers.ip-frontend.entryPoints=websecure"
      - "traefik.http.routers.ip-frontend.tls=true"
      - "traefik.http.services.ip-frontend.loadbalancer.server.port=80"

  backend:
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ip-backend.rule=PathPrefix(`/ip/api`)"
      - "traefik.http.routers.ip-backend.entryPoints=websecure"
      - "traefik.http.routers.ip-backend.tls=true"
      - "traefik.http.services.ip-backend.loadbalancer.server.port=8000"
      
networks:
  proxy_net:
    external: true

