# PATH: docker-compose.override.yml

services:
  db:
    container_name: "postgres-dev"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build:
      args:
        SERVICE_NAME: "${SERVICE_NAME}"
        BACKEND_PORT: "${BACKEND_PORT}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "5678:5678"
    volumes:
      - ./backend/app:/app/app
      - ./backend/tmp:/app/tmp
    command: [
      "python",
      "-m",
      "debugpy",
      "--listen",
      "0.0.0.0:5678",
      "-m",
      "uvicorn",
      "app.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "${BACKEND_PORT}",
      "--reload"
    ]
  frontend:
    build:
      target: dev
      args:
        SERVICE_NAME: "${SERVICE_NAME}"
        FRONTEND_PORT: "${FRONTEND_PORT}"
        BACKEND_PORT: "${BACKEND_PORT}"
        ENVIRONMENT: "development"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
  pgadmin:
    container_name: "pgadmin-dev"
    environment:
      - "PGADMIN_DEV_PORT=${PGADMIN_DEV_PORT}"
    ports:
      - "${PGADMIN_DEV_PORT}:80"