# PATH: docker-compose.override.yml

services:
  frontend:
    build:
      target: dev
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true" # Required for hot-reloading in Windows
      CHOKIDAR_INTERVAL: "1000" # Required for hot-reloading in Windows
    volumes:
      - ./frontend/src:/app/src
  backend:
    ports:
      - "8000:8000"
      - "5678:5678"  # Puerto para el depurador
    volumes:
      - ./backend/app:/app/app
      - ./backend/tmp:/app/tmp # Para almacenar archivos temporales de depuración
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


