# PATH: docker-compose.yml

services:
  db:
    image: postgres:15
    container_name: "postgres"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypass"
      POSTGRES_DB: "mydatabase"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: "${SERVICE_NAME}-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: "${SERVICE_NAME}"
      BACKEND_PORT: "${BACKEND_PORT}"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypass"
      POSTGRES_DB: "mydatabase"
      POSTGRES_SERVER: "db"
      POSTGRES_PORT: "5432"
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: >
      bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}
      "

  frontend:
    container_name: "${SERVICE_NAME}-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: "${SERVICE_NAME}"
      FRONTEND_PORT: "${FRONTEND_PORT}"
      BACKEND_PORT: "${BACKEND_PORT}"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./archivo/import_data:/import_data

volumes:
  pgdata:
  pgadmin_data: