# PATH: docker-compose.prod.yml

services:
  frontend:
    environment:
      SERVICE_NAME: "${SERVICE_NAME}"
    build:
      target: prod
      args:
        SERVICE_NAME: "${SERVICE_NAME}"
        FRONTEND_PORT: "${FRONTEND_PORT}"
        ENVIRONMENT: "production"
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}-frontend.rule=PathPrefix(`/${SERVICE_NAME}`)"
      - "traefik.http.routers.${SERVICE_NAME}-frontend.entryPoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-frontend.tls=true"
      - "traefik.http.services.${SERVICE_NAME}-frontend.loadbalancer.server.port=80"

  backend:
    build:
      args:
        SERVICE_NAME: "${SERVICE_NAME}"
        BACKEND_PORT: "${BACKEND_PORT}"
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}-backend.rule=PathPrefix(`/${SERVICE_NAME}/api`)"
      - "traefik.http.routers.${SERVICE_NAME}-backend.entryPoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-backend.tls=true"
      # mapeamos el puerto interno del contenedor (backend) -> traefik
      - "traefik.http.services.${SERVICE_NAME}-backend.loadbalancer.server.port=${BACKEND_PORT}"

networks:
  proxy_net:
    external: true
