# PATH: docker-compose.prod.yml

services:
  frontend:
    build:
      target: prod
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}-frontend.rule=PathPrefix(`/${SERVICE_NAME}`)"
      - "traefik.http.routers.${SERVICE_NAME}-frontend.entryPoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-frontend.tls=true"
      - "traefik.http.services.${SERVICE_NAME}-frontend.loadbalancer.server.port=80"

  backend:
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}-backend.rule=PathPrefix(`/${SERVICE_NAME}/api`)"
      - "traefik.http.routers.${SERVICE_NAME}-backend.entryPoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-backend.tls=true"
      - "traefik.http.services.${SERVICE_NAME}-backend.loadbalancer.server.port=8000"

      
networks:
  proxy_net:
    external: true

