# PATH: docker-compose.yml

services:
  frontend:
    container_name: ${SERVICE_NAME}-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    container_name: ${SERVICE_NAME}-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
