# PATH: backend/alembic/versions/0273f724db45_1_1_optional_entre_imputaciones_y_.py

"""1:1 optional entre Imputaciones y Extraciclos

Revision ID: 0273f724db45
Revises: 473635d290de
Create Date: 2024-01-26 13:53:05.890762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0273f724db45'
down_revision: Union[str, None] = '473635d290de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
