# PATH: backend/alembic/versions/0a665fd4565a_añadir_tipos_de_imputaciones_xx_gg_o_cn.py

"""Añadir tipos de imputaciones: XX, GG o Cn

Revision ID: 0a665fd4565a
Revises: 3f5073e71d07
Create Date: 2025-02-12 13:58:34.811474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a665fd4565a'
down_revision: Union[str, None] = '3f5073e71d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TiposOrdenes',
    sa.Column('TipoOrden', sa.String(length=2), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=True),
    sa.Column('Grupo', sa.Integer(), nullable=True),
    sa.Column('NombreGrupo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('TipoOrden')
    )
    op.create_index(op.f('ix_TiposOrdenes_TipoOrden'), 'TiposOrdenes', ['TipoOrden'], unique=False)
    op.add_column('Imputaciones', sa.Column('TipoImput', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'Imputaciones', 'TiposOrdenes', ['TipoImput'], ['TipoOrden'])
    op.add_column('Sap_Orders', sa.Column('TipoTarea', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'Sap_Orders', 'TiposOrdenes', ['TipoTarea'], ['TipoOrden'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Sap_Orders', type_='foreignkey')
    op.drop_column('Sap_Orders', 'TipoTarea')
    op.drop_constraint(None, 'Imputaciones', type_='foreignkey')
    op.drop_column('Imputaciones', 'TipoImput')
    op.drop_index(op.f('ix_TiposOrdenes_TipoOrden'), table_name='TiposOrdenes')
    op.drop_table('TiposOrdenes')
    # ### end Alembic commands ###
