# PATH: backend/alembic/versions/150d19fc3cdc_añadir_campo_cargado_tarea_real_y_.py

"""Añadir campo cargado_tarea_real y ajustar Cargado_Sap

Revision ID: 150d19fc3cdc
Revises: 2b980b53ad6b
Create Date: 2025-02-11 11:57:17.978691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '150d19fc3cdc'
down_revision: Union[str, None] = '2b980b53ad6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tabla_Central', sa.Column('cargadoEnTareaReal', sa.Boolean(), nullable=True))
    op.alter_column('Tabla_Central', 'Cargado_SAP', server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tabla_Central', 'cargadoEnTareaReal')
    op.alter_column('Tabla_Central', 'Cargado_SAP', server_default=None)
    # ### end Alembic commands ###
