# PATH: backend/alembic/versions/397943659c03_borrar_tabla_gg_orders.py

"""borrar tabla GG Orders

Revision ID: 397943659c03
Revises: a7657aca28f9
Create Date: 2024-02-01 11:24:51.188693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397943659c03'
down_revision: Union[str, None] = 'a7657aca28f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_GG_Orders_ID', table_name='GG_Orders')
    op.drop_table('GG_Orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GG_Orders',
    sa.Column('ID', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Order', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Operation', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OperationActivity', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TipoIndirecto', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TipoMotivo', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__GG_Order__3214EC274A826C97')
    )
    op.create_index('ix_GG_Orders_ID', 'GG_Orders', ['ID'], unique=False)
    # ### end Alembic commands ###
