# PATH: backend/alembic/versions/3f5073e71d07_añadir_timestamps_a_transaccionales.py

"""Añadir timestamps a transaccionales

Revision ID: 3f5073e71d07
Revises: 150d19fc3cdc
Create Date: 2025-02-11 12:07:10.022968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5073e71d07'
down_revision: Union[str, None] = '150d19fc3cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sap_Orders', sa.Column('TimestampInput', sa.DateTime(), nullable=True))
    op.add_column('Tabla_Central', sa.Column('TimestampInput', sa.DateTime(), nullable=True))
    op.alter_column('Tabla_Central', 'cargadoEnTareaReal', server_default=sa.true())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tabla_Central', 'TimestampInput')
    op.drop_column('Sap_Orders', 'TimestampInput')
    op.alter_column('Tabla_Central', 'cargadoEnTareaReal', sa.false())
    # ### end Alembic commands ###
