# PATH: backend/alembic/versions/473635d290de_nullable_false_para_extraciclos_.py

# alembic/versions/473635d290de_nullable_false_para_extraciclos_.py

"""nullable=False para Extraciclos.CentroTrabajo y TareaBaan

Revision ID: 473635d290de
Revises: b8b5d58d0e8e
Create Date: 2024-01-24 15:52:05.609590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473635d290de'
down_revision: Union[str, None] = 'b8b5d58d0e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Extraciclos', 'CentroTrabajo',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    op.alter_column('Extraciclos', 'TareaBaan',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Extraciclos', 'TareaBaan',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    op.alter_column('Extraciclos', 'CentroTrabajo',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
