# PATH: backend/alembic/versions/5154326e35aa_migracion_inicial.py

# alembic/versions/5154326e35aa_migracion_inicial.py

"""migracion_inicial

Revision ID: 5154326e35aa
Revises: 
Create Date: 2024-01-11 11:12:27.218371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5154326e35aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects_Dictionary',
    sa.Column('ProyectoBaan', sa.String(length=255), nullable=False),
    sa.Column('ProyectoSap', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ProyectoBaan')
    )
    op.create_index(op.f('ix_Projects_Dictionary_ProyectoBaan'), 'Projects_Dictionary', ['ProyectoBaan'], unique=False)
    op.create_table('Sap_Orders',
    sa.Column('ID', sa.BIGINT(), nullable=False),
    sa.Column('OperationActivityFull', sa.String(), nullable=True),
    sa.Column('EffectivityFull', sa.String(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Operation', sa.String(), nullable=True),
    sa.Column('OperationActivity', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Project', sa.String(), nullable=True),
    sa.Column('Area', sa.String(), nullable=True),
    sa.Column('Vertice', sa.String(), nullable=True),
    sa.Column('CarNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Sap_Orders_ID'), 'Sap_Orders', ['ID'], unique=False)
    op.create_table('Imputaciones',
    sa.Column('ID', sa.BIGINT(), nullable=False),
    sa.Column('FechaImp', sa.Date(), nullable=True),
    sa.Column('CodEmpleado', sa.String(), nullable=True),
    sa.Column('Timpu', sa.String(), nullable=True),
    sa.Column('Horas', sa.Float(), nullable=True),
    sa.Column('Proyecto', sa.String(length=255), nullable=True),
    sa.Column('TipoCoche', sa.String(), nullable=True),
    sa.Column('NumCoche', sa.String(), nullable=True),
    sa.Column('CentroTrabajo', sa.String(), nullable=True),
    sa.Column('Tarea', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Proyecto'], ['Projects_Dictionary.ProyectoBaan'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Imputaciones_ID'), 'Imputaciones', ['ID'], unique=False)
    op.create_table('Tabla_Central',
    sa.Column('ID', sa.BIGINT(), nullable=False),
    sa.Column('Employee_Number', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('HourType', sa.String(), nullable=True),
    sa.Column('ProductionOrder', sa.BIGINT(), nullable=True),
    sa.Column('Operation', sa.String(), nullable=True),
    sa.Column('OperationActivity', sa.String(), nullable=True),
    sa.Column('Hours', sa.Float(), nullable=True),
    sa.Column('Cargado_SAP', sa.Boolean(), nullable=True),
    sa.Column('imputacion_id', sa.BIGINT(), nullable=True),
    sa.Column('sap_order_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['imputacion_id'], ['Imputaciones.ID'], ),
    sa.ForeignKeyConstraint(['sap_order_id'], ['Sap_Orders.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Tabla_Central_ID'), 'Tabla_Central', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tabla_Central_ID'), table_name='Tabla_Central')
    op.drop_table('Tabla_Central')
    op.drop_index(op.f('ix_Imputaciones_ID'), table_name='Imputaciones')
    op.drop_table('Imputaciones')
    op.drop_index(op.f('ix_Sap_Orders_ID'), table_name='Sap_Orders')
    op.drop_table('Sap_Orders')
    op.drop_index(op.f('ix_Projects_Dictionary_ProyectoBaan'), table_name='Projects_Dictionary')
    op.drop_table('Projects_Dictionary')
    # ### end Alembic commands ###
