# PATH: backend/alembic/versions/8d15cf072789_cambiar_la_longitud_de_centrotrabajo.py

# alembic/versions/8d15cf072789_cambiar_la_longitud_de_centrotrabajo.py

"""cambiar la longitud de CentroTrabajo

Revision ID: 8d15cf072789
Revises: be3b2ec4537d
Create Date: 2024-01-16 11:05:41.687769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d15cf072789'
down_revision: Union[str, None] = 'be3b2ec4537d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Imputaciones', 'CentroTrabajo',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Imputaciones', 'CentroTrabajo',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
