# PATH: backend/alembic/versions/8f928a8a99b4_relacion_centrotrabajo_area.py

# alembic/versions/8f928a8a99b4_relacion_centrotrabajo_area.py

"""relacion CentroTrabajo Area

Revision ID: 8f928a8a99b4
Revises: 8d15cf072789
Create Date: 2024-01-16 11:19:16.233385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f928a8a99b4'
down_revision: Union[str, None] = '8d15cf072789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Areas',
    sa.Column('CentroTrabajo', sa.String(length=32), nullable=False),
    sa.Column('Area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CentroTrabajo')
    )
    op.create_index(op.f('ix_Areas_CentroTrabajo'), 'Areas', ['CentroTrabajo'], unique=False)
    op.add_column('Imputaciones', sa.Column('area_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'Imputaciones', 'Areas', ['area_id'], ['CentroTrabajo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Imputaciones', type_='foreignkey')
    op.drop_column('Imputaciones', 'area_id')
    op.drop_index(op.f('ix_Areas_CentroTrabajo'), table_name='Areas')
    op.drop_table('Areas')
    # ### end Alembic commands ###
