# PATH: backend/alembic/versions/93cb897356a6_opminc.py

"""OpMinC

Revision ID: 93cb897356a6
Revises: 0a665fd4565a
Create Date: 2025-04-08 13:39:14.641801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cb897356a6'
down_revision: Union[str, None] = '0a665fd4565a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Areas', sa.Column('OpMinC', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Areas', 'OpMinC')
    # ### end Alembic commands ###
