# PATH: backend/alembic/versions/a5295bc970b9_columna_activeorder_en_saporders_para_.py

"""Columna ActiveOrder en SapOrders para poder dejar obsoletas las órdenes sin borrarlas del sistema

Revision ID: a5295bc970b9
Revises: f0d76de0d454
Create Date: 2024-03-18 08:20:41.664639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5295bc970b9'
down_revision: Union[str, None] = 'f0d76de0d454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sap_Orders', sa.Column('ActiveOrder', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sap_Orders', 'ActiveOrder')
    # ### end Alembic commands ###
