# PATH: backend/alembic/versions/a7657aca28f9_tablas_gg.py

"""Tablas GG

Revision ID: a7657aca28f9
Revises: 0273f724db45
Create Date: 2024-02-01 10:07:56.438643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7657aca28f9'
down_revision: Union[str, None] = '0273f724db45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GG_Orders',
    sa.Column('ID', sa.BIGINT(), nullable=False),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Operation', sa.String(), nullable=True),
    sa.Column('OperationActivity', sa.String(), nullable=True),
    sa.Column('TipoIndirecto', sa.String(), nullable=True),
    sa.Column('TipoMotivo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_GG_Orders_ID'), 'GG_Orders', ['ID'], unique=False)
    op.add_column('Areas', sa.Column('OpGG', sa.String(), nullable=True))
    op.add_column('Imputaciones', sa.Column('TipoIndirecto', sa.String(), nullable=True))
    op.add_column('Imputaciones', sa.Column('TipoMotivo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Imputaciones', 'TipoMotivo')
    op.drop_column('Imputaciones', 'TipoIndirecto')
    op.drop_column('Areas', 'OpGG')
    op.drop_index(op.f('ix_GG_Orders_ID'), table_name='GG_Orders')
    op.drop_table('GG_Orders')
    # ### end Alembic commands ###
