# alembic/versions/b8b5d58d0e8e_adici�n_de_la_tabla_extraciclos_y_.py

"""Adición de la tabla Extraciclos y EventListeners para la generación de AreaTarea, el ID que la relaciona con Imputaciones

Revision ID: b8b5d58d0e8e
Revises: 8f928a8a99b4
Create Date: 2024-01-24 15:28:48.423943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b5d58d0e8e'
down_revision: Union[str, None] = '8f928a8a99b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Extraciclos',
    sa.Column('AreaTarea', sa.String(length=64), nullable=False),
    sa.Column('CentroTrabajo', sa.String(length=32), nullable=True),
    sa.Column('TipoCNC', sa.String(length=32), nullable=True),
    sa.Column('TareaBaan', sa.String(length=32), nullable=True),
    sa.Column('OASAP', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('AreaTarea')
    )
    op.create_index(op.f('ix_Extraciclos_AreaTarea'), 'Extraciclos', ['AreaTarea'], unique=False)
    op.add_column('Imputaciones', sa.Column('AreaTarea', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'Imputaciones', 'Extraciclos', ['AreaTarea'], ['AreaTarea'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Imputaciones', type_='foreignkey')
    op.drop_column('Imputaciones', 'AreaTarea')
    op.drop_index(op.f('ix_Extraciclos_AreaTarea'), table_name='Extraciclos')
    op.drop_table('Extraciclos')
    # ### end Alembic commands ###
