# alembic/versions/be3b2ec4537d_añadiendo_columna_tareaasoc_en_.py

"""aÃ±adiendo columna TareaAsoc en imputaciones para detectar extraciclos en origen

Revision ID: be3b2ec4537d
Revises: 5154326e35aa
Create Date: 2024-01-15 15:27:40.518797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3b2ec4537d'
down_revision: Union[str, None] = '5154326e35aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Imputaciones', sa.Column('TareaAsoc', sa.String(), nullable=True))
    # ### end Alembic commands ###
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Imputaciones', 'TareaAsoc')
    # ### end Alembic commands ###
