# PATH: backend/alembic/versions/f0d76de0d454_añadir_tipoindirecto_y_tipomotivo_a_.py

"""añadir TipoIndirecto y TipoMotivo a SapOrders

Revision ID: f0d76de0d454
Revises: 397943659c03
Create Date: 2024-02-01 11:27:26.904376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d76de0d454'
down_revision: Union[str, None] = '397943659c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sap_Orders', sa.Column('TipoIndirecto', sa.String(), nullable=True))
    op.add_column('Sap_Orders', sa.Column('TipoMotivo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sap_Orders', 'TipoMotivo')
    op.drop_column('Sap_Orders', 'TipoIndirecto')
    # ### end Alembic commands ###
